<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>Core_Conductor</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PackageId>ContactCI.Maestro.CoreConductor</PackageId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ContactCI.Maestro.libcore" Version="2.0.1" />
    </ItemGroup>

</Project>
