stages:
  - install_dependencies
  - build
  - release

variables:
  MSVC_PATH: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build"
  FF_USE_FASTZIP: "true"
  CACHE_COMPRESSION_LEVEL: "fastest"
  MSYS_PATH: "$CI_PROJECT_DIR\\msys"
  BUILD_MSVC: "true"
  BUILD_MINGW: "true"

install_mingw:
  stage: install_dependencies
  tags:
    - "windows"
  cache:
    key: $CI_COMMIT_BRANCH
    paths:
      - "msys/"
      - "vcpkg/"
  script:
    - echo "checking for msys"
    - |
      if (-not (Test-Path $env:MSYS_PATH)) {
        echo "Downloading msys2 to $env:MSYS_PATH"
        mkdir "$env:MSYS_PATH"
        Invoke-WebRequest -Uri https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe -OutFile msys.exe
        Start-Process -Wait -NoNewWindow -FilePath .\msys.exe -ArgumentList '-y', -o"$env:MSYS_PATH"
        Remove-Item msys.exe
      }
    - $env:Path += ";$env:MSYS_PATH\msys64\bin\"
    - $env:Path += ";$env:MSYS_PATH\msys64\usr\bin\"
    - $env:Path += ";$env:MSYS_PATH\msys64\mingw64\bin\"
    - $env:Path += ";$env:MSYS_PATH\msys64\mingw64\usr\bin\"
    # ' ' 'Syuu'
    #protobuf protobuf-devel mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-toolchain mingw-w64-x86_64-make mingw-w64-x86_64-ninja
    - powershell -command "& bash -lc ' '"
    - powershell -command "& bash -lc 'pacman --noconfirm -Syuu'"
    - powershell -command "& bash -lc 'pacman --noconfirm --needed -S mingw-w64-x86_64-make ninja mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-toolchain'"

    #- restart-service *docker*
    #- t="$TOKEN" gitlab-runner -l debug register --non-interactive --url ${GITLAB_URL} --registration-token ${t} --executor docker --docker-image alpine --name docker-runner --docker-pull-policy if-not-present --locked=false --run-untagged=false --docker-privileged=false --limit 0 --tag-list docker

install_msvc:
  stage: install_dependencies
  rules:
    - if: $BUILD_MSVC == "true"
  tags:
    - "windows"
  cache:
    key: $CI_COMMIT_BRANCH
    paths:
      - "msys/"
      - "vcpkg/"
  script:
    - echo "Setting up vcpkg"
    # Download vcpkg if it’s not already present in the cache
    - |
      if (-not (Test-Path vcpkg)) {
        git clone https://github.com/microsoft/vcpkg vcpkg
      }
    - cd vcpkg
    - .\bootstrap-vcpkg.bat
    - echo "Installing dependencies using vcpkg"
    - .\vcpkg install protobuf --triplet x64-windows

build_mingw:
  stage: build
  rules:
    - if: $BUILD_MINGW == "true"
  tags:
    - "windows"
  cache:
    key: $CI_COMMIT_BRANCH
    paths:
      - "msys/"
      - "vcpkg/"
    policy: pull
  before_script:
    - $env:GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no'
    - git submodule update --init --recursive
  script:
    - $env:Path += ";$env:MSYS_PATH\msys64\mingw64\bin\;$env:MSYS_PATH\msys64\mingw64\usr\bin\;$env:MSYS_PATH\msys64\bin\;$env:MSYS_PATH\msys64\usr\bin\"
    - Expand-Archive -Path protobuf.zip -DestinationPath .
    - cmake "-DCMAKE_PREFIX_PATH=$env:CI_PROJECT_DIR/protobuf" "-DCMAKE_BUILD_TYPE=Release" -S . -B build/release-mingw
    - cmake --build build/release-mingw --target ccic -j10
  artifacts:
    paths:
      - "build/*/*.dll"

build_msvc:
  stage: build
  rules:
    - if: $BUILD_MSVC == "true"
  cache:
    key: $CI_COMMIT_BRANCH
    paths:
      - "msys/"
      - "vcpkg/"
    policy: pull
  before_script:
    - $env:GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no'
    - git submodule update --init --recursive
  script:
    - echo "Building project using MSVC"
    - powershell -Command "& 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat' x64"
    #- powershell -Command "& 'C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\vcvars64.bat'"
    # Assuming you have a CMake project, configure and build
    #- git submodule update --init --recursive
    #- $env:Path += ";$env:CI_PROJECT_DIR\cmake\cmake-3.28.6-windows-x86_64\bin"
    - $env:Path += ";$env:MSYS_PATH\msys64\mingw64\bin\;$env:MSYS_PATH\msys64\mingw64\usr\bin\;$env:MSYS_PATH\msys64\bin\;$env:MSYS_PATH\msys64\usr\bin\"
    - cmake -DCMAKE_TOOLCHAIN_FILE="$env:CI_PROJECT_DIR/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_BUILD_TYPE=Release" -A x64 -S . -B build/release-msvc
    - cmake --build . --config Release


upload package:
  stage: release
  image: alpine
  #dependencies:
  #  - build_mingw
  tags:
    - docker
  # uploads the output zip to package registry for semi-permanent retention
  script:
    - apk add zip curl
    - BUILD_VERSION=$CI_COMMIT_SHORT_SHA
    - FILENAME=build.zip
    - echo $FILENAME
    - ls build
    - URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${BUILD_VERSION}/${FILENAME}"
    - echo $URL
    - zip -r ${FILENAME} build/*
    - echo "URL=${URL}" >> variables.env
    - echo "FILENAME=${FILENAME}" >> variables.env
    - cat variables.env
    - 'curl --fail-with-body --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "build.zip" "$URL"'
  only:
    - tags
  artifacts:
    reports:
      dotenv: variables.env

release:
  stage: release
  tags:
    - docker
  # only creates a release if a tag is explicitly pushed
  only:
    - tags
  needs: [upload package]
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo $FILENAME
    - echo $URL
    - echo "running release_job for ${CI_COMMIT_TAG}"
    - export FILENAME=build.zip
    - echo $FILENAME
    - export URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${BUILD_VERSION}/${FILENAME}"
    - echo $URL
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: 'Release DLLs: [$FILENAME]($URL)'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: '$FILENAME'
          url: '$URL'
