syntax = "proto3";

option csharp_namespace = 'ContactCI.Communication.Messages';

//Write an arbitrary payload to configuration area of device EEPROM
//Format is device-specific, use care!
message DeviceConfigMessage {
  uint32 chipID = 1;
  bytes data = 2;
}

//request existing config on device
message DeviceConfigRequestMessage {
  uint32 chipID = 1;
}

//notify device we have a firmware update
message FirmwareUpdateRequestMessage {
  uint32 chipID = 1;      //ID of the processor to update
  uint32 imageSize = 2;   //length in bytes of the firmware image
}

//device will respond with status
message FirmwareUpdateNegotiateMessage {
  uint32 chipId = 1;
  bool ready = 2;         //if not ready, try again later
  uint32 packetSize = 3;  //device may have limited buffer space
}

//segment of firmware image
message FirmwareUpdateChunkMessage {
  uint32 chipId = 1;
  bytes data = 2;
}

//How did the update go?
message FirmwareUpdateResponseMessage {
  enum fwResponse{
    error = 0;            //unspecified error
    checksumMismatch = 1; //checksum failure
    readyReceive = 2;     //ready for next packet
    busy = 3;             //busy writing, please wait
    OK = 4;               //OK
  }
  fwResponse status = 1;  //status field
  uint32 chipId = 2;
}

//host can request firmware by sending an empty version
//device(s) will respond with their version
message FirmwareVersionMessage {
  uint32 chipId = 1;
  string version = 2;     //generally expressed as semVer eg: 1.2.123
}

message DevicePropertiesRequestMessage {
  // intentionally empty
}

// This is for non-bluetooth devices, as we use SDP records for Bluetooth
message DevicePropertiesResponseMessage {
  string productLine = 1;
  string serialNumber = 2;
  bool isRight = 3;
  uint32 size = 4; // ContactCI.Service.Device.Properties.DeviceProperties.GloveSize enum integer value
}