syntax = "proto3";

option csharp_namespace = 'ContactCI.Communication.Messages';

message DeviceListRequestMessage {
    // intentionally empty
}

message DeviceListResponseMessage {
    repeated DeviceDescriptionMessage devices = 1;
}

// no opcode needed; part of DeviceListResponseMessage
message DeviceDescriptionMessage {
    string productLine = 1;
    string serialNumber = 2;
    bool isRight = 3;
    bool isConnected = 4;
}

message ClientListRequestMessage {
    // Intentionally empty
}

message ClientListResponseMessage {
    repeated ClientDescriptionMessage clients = 1;
}

// no opcode needed; part of ClientListResponseMessage
message ClientDescriptionMessage {
    uint32 processId = 1;
    string processName = 2;
}

message ServiceInfoRequestMessage {
    // intentionally empty
}

message ServiceInfoResponseMessage {
    string version = 1;
    bool isInteractive = 2;
}