syntax = "proto3";

//Immediately set the given dimension:actuators to the set value
//If sent between MDHTOpen and -Close messages, inserts a haptic frame into the MDHT
message SetDimensionMessage {
  uint32 dimension = 1;   //dimension identifier
  uint32 flags = 2;       //optional flags for dimension parser
  uint32 bitmask = 3;     //bitmask for actuators
  bytes value = 4;        //raw haptic value(s)
}

//Open a MultiDimensional Haptic Transaction
//This queues haptic frames from many dimensions so playback can be synchronized
message MDHTOpenMessage {
  uint32 id = 1;        //arbitrary identifier for this transaction
}

//Closes a MDHT transaction
//After closing the transaction, the effect is ready to play
message MDHTCloseMessage {
  uint32 id = 1;        //identifier to close
}

//Begins playback of a MDHT effect
message MDHTPlayMessage {
  uint32 id = 1;        //identifier to play
}

//Erase a previously stored MDHT
message MDHTEraseMessage {
  uint32 id = 1;        //identifier to erase
}

//Pause playback of a MDHT effect
message MDHTSuspendMessage {
  uint32 id = 1;        //identifier to pause
}

//Resume playback of a MDHT effect
message MDHTResumeMessage {
  uint32 id = 1;
}

//Stop playback of a MDHT effect and does not store resume state
message MDHTStopMessage {
  uint32 id = 1;
}

//Suspend haptics on one dimension
message DimensionSuspendMessage {
  uint32 dimension = 1;
  uint32 flags = 2;
  uint32 bitmask = 3;
}

//Resume haptics on one dimension
message DimensionResumeMessage {
  uint32 dimension = 1;
  uint32 flags = 2;
  uint32 bitmask = 3;
}

//Device periodically reports the current state of haptic playback
message DimensionStatusMessage {
  uint32 dimension = 1;   //which dimension is reporting?
  uint32 flags = 2;       //protocol flags
  bytes values = 3;       //raw haptic values for each actuator
}
