#!/usr/bin/env bash
# =============================================================================
# build-protobuf.sh
# -----------------------------------------------------------------------------
# Builds protobuf (protoc + static libprotobuf) from source with the MSYS2
# MINGW64 toolchain and installs it into a prefix that CMake can find through
# -DCMAKE_PREFIX_PATH. Used by install.ps1, and therefore by CI.
#
# Why from source: the repository used to carry protobuf.zip, prebuilt with
# GCC 13, which stopped working once MSYS2's libstdc++ dropped the
# std::call_once internals it referenced. A from-source build always matches
# the compiler in use.
#
# Run from an MSYS2 MINGW64 shell (install.ps1 does this for you):
#     tools/build-protobuf.sh [prefix]          # default prefix: ./protobuf
#
# The prefix gets a .build-stamp naming the protobuf version and the compiler.
# install.ps1 and build.ps1 compare it against the current compiler and rebuild
# when they differ.
# =============================================================================
set -euo pipefail

PROTOBUF_VERSION="3.21.12"
PROTOBUF_TAG="v21.12"
PROTOBUF_SHA256="4eab9b524aa5913c6fffb20b2a8abf5ef7f95a80bc0701f3a6dbb4c607f73460"
PROTOBUF_URL="https://github.com/protocolbuffers/protobuf/releases/download/${PROTOBUF_TAG}/protobuf-cpp-${PROTOBUF_VERSION}.tar.gz"

die() { echo "build-protobuf.sh: $*" >&2; exit 1; }

[ "${MSYSTEM:-}" = "MINGW64" ] || die "run this from an MSYS2 MINGW64 shell (MSYSTEM is '${MSYSTEM:-unset}')"
for tool in gcc g++ cmake ninja tar sha256sum; do
    command -v "$tool" >/dev/null || die "'$tool' not found. Install it with: pacman -S --needed mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja"
done

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
prefix="${1:-$script_dir/../protobuf}"
mkdir -p "$prefix"
prefix="$(cd "$prefix" && pwd)"

# The prefix is emptied before installing, so it must be empty or already a
# protobuf install - never, say, the repository root from a mistyped argument.
if [ -n "$(ls -A "$prefix")" ] && [ ! -d "$prefix/include/google/protobuf" ]; then
    die "$prefix is not empty and does not look like a protobuf install - refusing to overwrite it"
fi

stamp="protobuf ${PROTOBUF_VERSION} ${MSYSTEM} gcc $(gcc -dumpfullversion)"
if [ -f "$prefix/.build-stamp" ] && [ "$(cat "$prefix/.build-stamp")" = "$stamp" ]; then
    echo "protobuf is up to date in $prefix ($stamp)"
    exit 0
fi

# Object paths in protobuf's build tree are ~120 characters deep, and ar.exe
# fails ("No such file or directory") past Windows' 260-character limit. The
# default /tmp of a C:\msys64 install is short enough; for an MSYS2 under a
# deep path, point TMPDIR somewhere short.
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# MSYS's own curl, not MINGW64's (first on PATH once cmake pulls it in): the
# MINGW64 CA bundle is generated by a pacman hook, and a fresh install has been
# seen with it empty, failing every HTTPS download with curl error 77.
echo "Downloading protobuf ${PROTOBUF_VERSION}"
/usr/bin/curl -fsSL --retry 3 -o "$work/src.tar.gz" "$PROTOBUF_URL"
echo "${PROTOBUF_SHA256}  $work/src.tar.gz" | sha256sum -c --quiet - || die "checksum mismatch for $PROTOBUF_URL"
tar -xzf "$work/src.tar.gz" -C "$work"

# Static libraries, so libcci.dll carries protobuf inside it. protoc is linked
# statically as well so it runs outside an MSYS2 shell (CLion, plain cmd).
# zlib is off: libcci does not use gzip streams, and leaving it on would make
# the result depend on whether mingw-w64-x86_64-zlib happens to be installed.
echo "Configuring"
cmake -G Ninja -S "$work/protobuf-${PROTOBUF_VERSION}" -B "$work/build" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$prefix" \
    -DCMAKE_EXE_LINKER_FLAGS="-static" \
    -Dprotobuf_BUILD_TESTS=OFF \
    -Dprotobuf_BUILD_SHARED_LIBS=OFF \
    -Dprotobuf_WITH_ZLIB=OFF \
    -Wno-dev

echo "Building"
cmake --build "$work/build"

# Install into a clean prefix: stale headers or libraries from an older
# compiler or a hand-installed protobuf must not survive next to the new ones.
find "$prefix" -mindepth 1 -delete
cmake --install "$work/build"

"$prefix/bin/protoc.exe" --version
echo "$stamp" > "$prefix/.build-stamp"
echo "protobuf installed in $prefix ($stamp)"
